# Generated by Django 5.2.10 on 2026-01-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_date', models.DateField()),
                ('sequence', models.IntegerField(default=0, help_text='Order of this stop in the route')),
                ('estimated_arrival', models.TimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['route_date', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(default='Nairobi', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('additional_directions', models.TextField(help_text='Extra directions from landmark')),
                ('delivery_date', models.DateField()),
                ('delivery_time_start', models.TimeField()),
                ('delivery_time_end', models.TimeField()),
                ('items_description', models.TextField(help_text='Description of items to deliver')),
                ('status', models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Customer Confirmation'), ('CONFIRMED', 'Confirmed by Customer'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested'), ('ASSIGNED', 'Assigned to Rider'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered Successfully'), ('FAILED', 'Delivery Failed'), ('CANCELLED', 'Cancelled')], default='PENDING_CONFIRMATION', max_length=30)),
                ('confirmation_sms_sent', models.BooleanField(default=False)),
                ('confirmation_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_proof', models.TextField(blank=True, help_text='Delivery notes or proof')),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message_type', models.CharField(choices=[('CONFIRMATION', 'Order Confirmation Request'), ('RIDER_ASSIGNMENT', 'Rider Assignment Notification'), ('DELIVERY_SUCCESS', 'Delivery Success Notification'), ('DELIVERY_FAILED', 'Delivery Failed Notification')], max_length=30)),
                ('message_content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(blank=True, max_length=50)),
                ('response_received', models.BooleanField(default=False)),
                ('response_content', models.CharField(blank=True, max_length=10)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
