# Generated by Django 5.2.10 on 2026-01-14 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('riders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroute',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='riders.rider'),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.landmark'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='riders.rider'),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.landmark'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='orders',
            field=models.ManyToManyField(related_name='routes', to='orders.order'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='orders.order'),
        ),
    ]
